### ISSUE TITLE
AttributeError: 'Word2VecKeyedVectors' object has no attribute 'add_vectors'

### ISSUE THREAD

**Issue by sanjay-thiyagarajan** [subho406/OmniNet#10]
![issue1](https://user-images.githubusercontent.com/42594454/139787521-bcdbaaa6-30b4-4d1c-a80c-5cf78bc11dc7.png)

**Comment by sanjay-thiyagarajan** [comment]
The issue can be reproduced while running:
python predict.py model.pth caption --video somevideo.mp4

**Comment by tingchihc** [comment]
you must upgrade your gensim version. I can work on gensim-4.2.0
